
[build]
  base = "client"  
  command = "npm install && npm run build"  
  publish = "client/build"  

[build.environment]
NODE_VERSION = "14.x"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
